/**
 * Canonical human labels for the engine `adjustment_type` enum.
 *
 * Single source of truth shared by:
 *   - the Adjustments editor (ClientDetail → AdjustmentsTab) — the dropdown +
 *     the per-row badge.
 *   - the interactive what-if scenario builder (ClientDetail → Planning tab) —
 *     the per-mutation adjustment-type dropdown.
 *
 * Keep in sync with the `adjustment_type` enum in `lib/api-spec/openapi.yaml`
 * (the API rejects any type not in that enum). A missing label is non-fatal —
 * call sites fall back to the raw enum key — but every shipped type should have
 * a label so CPAs never see a raw snake_case key.
 */
export const ADJUSTMENT_TYPE_LABELS: Record<string, string> = {
  // FE2 (audit 2026-06-08) — the 36 adjustment types previously missing a
  // label (incl. all the T1.1 types) showed the raw enum key in the dropdown +
  // badges. Added below.
  unrecaptured_section_1250_gain: "Unrecaptured §1250 gain (25% rate)",
  collectibles_28_rate_gain: "Collectibles / §1202 gain (28% rate)",
  section_1231_lookback_loss: "§1231(c) 5-year lookback loss",
  months_without_minimum_coverage: "Months without minimum health coverage",
  household_employee_cash_wages: "Household employee cash wages (Schedule H)",
  household_employee_futa_wages: "Household employee FUTA wages (Schedule H)",
  clergy_housing_allowance: "Clergy housing allowance (SE-taxed, income-tax-exempt)",
  amt_credit_carryforward: "AMT credit carryforward (Form 8801)",
  charitable_carryforward_cash: "Charitable cash carryforward (prior year)",
  bonus_depreciation_basis: "Bonus depreciation basis (§168(k))",
  section_179_expense_election: "§179 expense election",
  hsa_employer_contribution: "HSA employer contribution",
  nondeductible_ira_contribution: "Nondeductible IRA contribution (Form 8606 basis)",
  roth_conversion_amount: "Roth conversion amount",
  roth_conversion_basis: "Roth conversion basis",
  roth_conversion_basis_within_5yr: "Roth conversion basis (within 5-year window)",
  roth_ira_distribution: "Roth IRA distribution",
  traditional_ira_distribution: "Traditional IRA distribution",
  mega_backdoor_roth_after_tax_contribution: "Mega-backdoor Roth after-tax contribution",
  nua_lump_sum_employer_stock: "NUA — lump-sum employer stock",
  augusta_rule_rent: "Augusta Rule rent (§280A(g))",
  foreign_source_taxable_income: "Foreign-source taxable income (Form 1116)",
  college_tuition_qualified: "Qualified college tuition (NY credit)",
  k12_education_expenses: "K-12 education expenses (IL credit)",
  annual_rent_paid: "Annual rent paid (renter's credit)",
  ca_renter_months: "CA renter — months rented",
  ga_disabled_home_purchase_cost: "GA disabled-access home purchase cost",
  ma_assessed_home_value: "MA assessed home value (circuit breaker)",
  ma_lead_paint_removal_cost: "MA lead-paint removal cost",
  ma_water_sewer_half: "MA water/sewer charges (½)",
  mi_home_heating_cost: "MI home-heating cost",
  mi_household_resources: "MI household resources",
  pa_eligibility_income: "PA eligibility income (Schedule SP)",
  oh_sdit_traditional_base: "OH SDIT — traditional base",
  part_year_use_w2_source: "Part-year: allocate W-2 by source state",
  part_year_use_full_source_allocation: "Part-year: full per-source allocation",
  deduction: "Deduction (above-the-line)",
  credit: "Credit (non-refundable)",
  additional_income: "Additional Income",
  withholding_adjustment: "Withholding / Estimated Payment",
  self_employment_income: "Self-Employment Income",
  investment_income: "Investment Income (NIIT)",
  qbi_income: "Qualified Business Income (QBI)",
  qbi_sstb_flag: "QBI — Specified Service Trade/Business (SSTB) flag",
  hi_employer_funded_pension: "HI — Employer-funded pension (excludable portion; employee 401(k)/IRA stays taxable)",
  ny_government_pension: "NY — Government pension (NYS/local/federal/military; IT-201 Line 26, fully excluded)",
  ct_ira_distribution: "CT — Non-Roth IRA portion of retirement income (50/75/100% by year; rest treated as pension/annuity 100%)",
  nonresident_source_allocation: "Multi-state — Source out-of-state K-1 business + rental real estate to its state for non-resident tax (flag; uses each K-1/rental sourceState)",
  part_year_income_pct_method: "Part-year — Use the IT-203/540NR income-% method for the resident-period tax in method-(a) states (flag; more accurate than day-prorated brackets)",
  oh_work_city_tax_paid: "OH — Municipal tax paid to WORK city (resident cross-city credit, ORC ch. 718)",
  nyc_ubt_business_income: "NYC — Unincorporated Business Tax: NYC-allocated net business income (4% UBT, Form NYC-202)",
  amt_preferences: "AMT Preferences (catch-all — line 2 misc)",
  amt_iso_bargain_element: "AMT — ISO Bargain Element (Form 6251 line 2k)",
  amt_state_tax_addback_override: "AMT — SALT Addback Override (Form 6251 line 2g; replaces auto)",
  amt_depreciation_adjustment: "AMT — MACRS-vs-ADS Depreciation (Form 6251 line 2i; regular − AMT depr, ± reversal)",
  amt_nol_carryforward: "AMT NOL Carryforward — ATNOLD (§56(d); AMT-basis NOL, capped at 90% of AMTI)",
  // Schedule A line items (itemized deductions)
  medical_expenses: "Medical/Dental Expenses (Sched A)",
  state_income_tax: "State Income Tax (Sched A SALT)",
  state_property_tax: "State Property Tax (Sched A SALT)",
  state_sales_tax: "State Sales Tax (Sched A SALT alt)",
  mortgage_interest: "Mortgage Interest (Sched A)",
  charitable_cash: "Charitable Cash (Sched A)",
  charitable_property: "Charitable Property (Sched A)",
  // Above-the-line retirement / health
  hsa_contribution: "HSA Contribution",
  ira_contribution_traditional: "Traditional IRA Contribution",
  ira_contribution_roth: "Roth IRA Contribution",
  self_employed_health_insurance_premiums: "Self-Employed Health Insurance Premiums (Form 7206, Sched 1 L17)",
  // OBBBA NEW deductions (Schedule 1-A → Form 1040 line 13b; reduce taxable income;
  // TY2025–2028). Senior $6k deduction is age-based (auto-applied from age fields).
  qualified_tips: "OBBBA — Qualified Tips (§224 'no tax on tips'; ≤$25k, phases out >$150k/$300k MAGI; TY2025–2028)",
  qualified_overtime: "OBBBA — Qualified Overtime premium (§225; ≤$12.5k single/$25k MFJ; phases out >$150k/$300k; FLSA 'half' only; TY2025–2028)",
  qualified_car_loan_interest: "OBBBA — Car Loan Interest (§163(h)(4); NEW US-assembled vehicle; ≤$10k, phases out >$100k/$200k; TY2025–2028)",
  home_sale_gross_gain_primary_residence: "Home Sale — Primary Residence Gross Gain (§121 exclusion auto-applied)",
  foreign_earned_income: "Foreign Earned Income — Primary Filer (Form 2555 §911, capped at $126,500 TY2024)",
  foreign_earned_income_spouse: "Foreign Earned Income — Spouse (MFJ only; same per-spouse cap)",
  nol_carryforward: "NOL Carryforward (post-TCJA 80% limit, IRC §172)",
  qsbs_gross_gain: "§1202 QSBS Gross Gain (exclusion auto-applied: max($10M, 10× basis))",
  qsbs_adjusted_basis: "§1202 QSBS Adjusted Basis (for the 10× cap)",
  section_1031_realized_gain: "§1031 Like-Kind Exchange — Realized Gain (real property only; aggregated across exchanges)",
  section_1031_boot_received: "§1031 Like-Kind Exchange — Boot Received (cash + non-like-kind; drives recognition = min(realized, boot))",
  iso_disqualifying_disposition_ordinary: "ISO Disqualifying Disposition — Ordinary Comp (IRC §421(b)/§422; not FICA-taxed; CPA hand-calcs min(FMV-at-exercise, sale-price) − strike)",
  espp_disqualifying_disposition_ordinary: "§423 ESPP Disqualifying Disposition — Ordinary Comp (FMV-at-purchase − purchase-price; not FICA-taxed per Rev Rul 71-52)",
  section_163j_business_interest_expense: "§163(j) Business Interest Expense — Gross (engine applies 30%-of-ATI cap)",
  section_163j_business_interest_income: "§163(j) Business Interest Income (adds to allowance dollar-for-dollar)",
  section_163j_carryforward_from_prior: "§163(j) Carryforward from Prior Year (stacks on gross, subject to same 30% cap)",
  section_163j_floor_plan_financing_interest: "§163(j) Floor Plan Financing Interest (100% allowed; never capped)",
  section_163j_gross_receipts: "§163(j) 3-yr Avg Gross Receipts — §448(c) (≤ threshold → small-biz EXEMPT, no 30% cap; $30M 2024 / $31M 2025 / $32M 2026)",
  section_461l_excess_loss_addback: "§461(l) Excess Business Loss Addback (TY2024 thresholds $305k/$610k; CPA pre-computes)",
  // Schedule C
  schedule_c_expenses: "Schedule C Business Expenses",
  // Credit-driving expenses
  dependent_care_expenses: "Dependent Care Expenses",
  qualified_education_expenses_aoc: "Education Expenses — AOC (per student)",
  qualified_education_expenses_llc: "Education Expenses — LLC",
  retirement_contributions_savers: "Retirement Contributions (Saver's Credit)",
  qualified_adoption_expenses: "Adoption Expenses (Form 8839 §23, per child)",
  adoption_special_needs: "Adoption — Special Needs (full credit, enter 1)",
  adoption_credit_carryforward: "Adoption Credit Carryforward (prior-year §23(c))",
  long_term_capital_gain: "Long-Term Capital Gain (additional — not on 1099-B/Sch D)",
  investment_interest_expense: "Investment Interest Expense (§163(d), Form 4952)",
  investment_interest_election_amount: "§163(d)(4)(B) Election — QDIV/LTCG as investment income",
  qualified_research_expenses: "R&D Qualified Research Expenses (§41, Form 6765)",
  qualified_research_expenses_prior_avg: "R&D — prior 3-yr avg QRE (ASC base; blank = startup 6%)",
  investment_interest_carryforward: "Investment Interest Carryforward (§163(d)(2), prior year)",
  rd_credit_carryforward: "R&D Credit Carryforward (§39, prior year)",
  general_business_credit_carryforward: "General Business Credit Carryforward (§39 §51/§45S, prior year)",
  schedule_c_section179_carryforward: "Schedule C §179 Carryforward (§179(b)(3)(B), prior year)",
  wotc_credit: "Work Opportunity Tax Credit (§51, Form 5884)",
  fmla_credit: "Paid Family & Medical Leave Credit (§45S, Form 8994)",
  scorp_reasonable_comp: "S-corp Reasonable Comp (RC Reports/BLS benchmark; G1.17)",
  schedule_c_depreciation: "Schedule C Depreciation (Form 4562 — reduces SE/QBI)",
  // Phase 1.5
  educator_expenses: "Educator Expenses (K-12, $300/educator)",
  student_loan_interest: "Student Loan Interest (1098-E)",
  foreign_tax_paid: "Foreign Tax Paid (1099-DIV Box 7)",
  residential_clean_energy: "Residential Clean Energy (§25D — solar/wind/geo, 30%)",
  energy_efficient_home: "Energy Efficient Home (§25C — windows/doors/insulation)",
  energy_efficient_heatpump: "Energy Efficient Heat Pump (§25C — heat pump/biomass)",
  ev_charger_property: "EV Charger Property (§30C — Form 8911)",
  // Phase 2
  capital_loss_carryforward_short: "Capital Loss Carryforward — Short-term (from prior year)",
  capital_loss_carryforward_long: "Capital Loss Carryforward — Long-term (from prior year)",
  schedule_e_rental_income: "Schedule E Rental Income (gross rents received)",
  schedule_e_rental_expenses: "Schedule E Rental Expenses (excl. depreciation)",
  schedule_e_macrs_depreciation: "Schedule E MACRS Depreciation",
  schedule_e_passive_loss_carryforward: "Schedule E Passive Loss Carryforward (prior year suspended)",
  k1_passive_loss_carryforward: "K-1 Passive Loss Carryforward (prior year suspended; non-rental-RE passive)",
  // T1.0c/d (2026-06-11) — newly API-reachable engine-read types
  qbi_loss_carryforward: "QBI Loss Carryforward (§199A(c)(2)(B) — prior-year net qualified business loss)",
  bonus_depreciation_basis_obbba: "Bonus Depreciation Basis — OBBBA 100% (post-1/19/2025 property)",
  qbi_w2_wages: "QBI W-2 Wages (Sch C §199A(b)(2) wage limit input)",
  qbi_ubia: "QBI UBIA of Qualified Property (Sch C §199A(b)(2) limit input)",
  qsbs_exclusion_pct: "QSBS Exclusion % Override (§1202 — 50/75 for pre-9/28/2010 stock)",
  out_of_state_muni_interest: "Out-of-state Municipal Interest (state-taxable addback)",
  us_treasury_interest: "U.S. Treasury Interest (state-exempt subtraction)",
  other: "Other",
};
