// ───────────────────────────────────────────────────────────────────────────
// IRS Account Monitor (Feature G-1) — transcript change detection + grounded
// notice-response drafting.
//
// THE PRODUCT: under a Form 8821 (Tax Information Authorization), a firm is
// authorized to RECEIVE — but not represent the taxpayer on — IRS account
// information. We periodically pull each consenting client's account / return /
// record-of-account transcripts from the IRS Transcript Delivery System (TDS,
// e-Services), diff them against the last snapshot, and surface meaningful
// changes (a new balance, a fresh CP notice, an audit/exam flag). For an
// actionable notice (e.g. a CP2000 Automated-Underreporter proposal), we then
// produce a CPA-reviewed DRAFT response that GROUNDS its argument in the firm's
// own computed return figures.
//
// ─── This module is PURE & Haven-portable ──────────────────────────────────
// NO Date / new Date() / Math.random / DB / fs / network / LLM call. The
// "as-of date" and the transcript data are PARAMETERS. The module computes over
// ALREADY-FETCHED structured transcript snapshots and emits a DETERMINISTIC,
// structured alert list + a deterministic, dollar-grounded draft-response
// object (subject + plain-text template + grounding facts + disclaimers).
//
// ─── Key seam (NOT implemented here) ───────────────────────────────────────
//   • TDS connector: the live pull from IRS e-Services Transcript Delivery
//     System is an authenticated, 8821-scoped route/adapter (per-firm CAF
//     credentials, transcript parsing) that lives OUTSIDE this pure module. It
//     hands us `TranscriptSnapshot`s; we never touch the network.
//   • LLM prose polish: "the LLM never touches the math." This module computes
//     every dollar and emits a deterministic template letter. A later route
//     MAY have the LLM polish the prose — ONLY under a recorded §7216 consent
//     (sending tax-return info to a model is a disclosure) — but it polishes
//     wording, never the figures, and this module makes no LLM call.
//
// ─── Compliance framing ────────────────────────────────────────────────────
//   • Form 8821 authorizes information access, NOT representation. This feature
//     MONITORS + DRAFTS; it never auto-files or auto-sends. (Filing a written
//     response / Power-of-Attorney representation needs a Form 2848 and is the
//     CPA's action.) Every draft is explicitly "DRAFT — CPA review required."
//   • CP2000 is an Automated Underreporter (AUR) PROPOSAL under IRC §6213(b)(2)
//     math/clerical-style processing, NOT a final assessment — the taxpayer may
//     dispute before it becomes a statutory notice of deficiency. Our draft
//     disputes with the firm's specific computed figure when the item WAS in
//     fact reported on the return.
//
// Transaction Codes (IRS Doc 6209, Section 8 — Master File codes):
//   150  Return filed / tax assessed            806  W-2 / 1099 withholding credit
//   290  Additional tax assessed                420  Examination of return (exam opened)
//   424  Examination request indicator          922  Review of unreported income (AUR)
//   971  Notice issued (misc.)                  640  Advance / estimated payment
// ───────────────────────────────────────────────────────────────────────────

import { type ComputedTaxReturn, toNum } from "./taxReturnEngine";

// ─── 1. Transcript line item ────────────────────────────────────────────────
export interface TranscriptLineItem {
  /** IRS Transaction Code, e.g. "150","806","922","420","290" (Doc 6209). */
  transactionCode: string;
  description: string;
  /** ISO date the TC posted (string — this module stays Date-free). */
  date: string;
  /** Signed dollar amount the TC carries (credits are commonly negative on a
   *  transcript; we diff on identity + absolute size, not sign). */
  amount: number;
}

// ─── 2. Transcript snapshot (the already-fetched TDS payload) ────────────────
export interface TranscriptSnapshot {
  taxYear: number;
  /** ISO date the transcript was generated by TDS ("as of" date). */
  asOfDate: string;
  /** Account balance per the transcript (positive = owed to the IRS). */
  accountBalance: number;
  lineItems: TranscriptLineItem[];
  notices: Array<{
    /** e.g. "CP2000","CP14","CP504","CP504B". */
    code: string;
    date: string;
    description: string;
    /** Additional tax/amount the notice proposes or demands, when present. */
    proposedAmount?: number;
  }>;
}

// ─── 3. Alert severity ───────────────────────────────────────────────────────
export type AlertSeverity = "info" | "action" | "urgent";

// ─── 4. Monitor alert ────────────────────────────────────────────────────────
export interface MonitorAlert {
  kind: "balance_change" | "new_notice" | "exam_flag" | "new_transaction";
  severity: AlertSeverity;
  title: string;
  detail: string;
  amount?: number;
  noticeCode?: string;
  recommendedAction: string;
}

// ─── Classification tables ───────────────────────────────────────────────────

/** Notice-code → severity + recommended action. CP504/CP504B are a Notice of
 *  Intent to Levy (collection escalation) → URGENT. CP2000 (AUR proposal) and
 *  CP14 (first balance-due notice) are time-sensitive but pre-enforcement →
 *  ACTION. Unknown codes default to ACTION (a posted notice always warrants a
 *  look). */
const NOTICE_SEVERITY: Record<string, AlertSeverity> = {
  CP2000: "action",
  CP2501: "action", // AUR initial contact (pre-CP2000)
  CP14: "action",
  CP501: "action", // reminder of balance due
  CP503: "action", // second reminder
  CP504: "urgent", // notice of intent to levy (state refund)
  CP504B: "urgent", // notice of intent to levy (assets) — business
  LT11: "urgent", // final notice of intent to levy + right to a hearing
};

function noticeSeverity(code: string): AlertSeverity {
  return NOTICE_SEVERITY[code.toUpperCase()] ?? "action";
}

function noticeAction(code: string): string {
  const c = code.toUpperCase();
  if (c === "CP2000" || c === "CP2501") {
    return "Reconcile the AUR-proposed items against the filed return; if the income was reported, draft a dispute citing the specific figures (this is a proposal under §6213(b), not a final assessment).";
  }
  if (c === "CP504" || c === "CP504B" || c === "LT11") {
    return "Time-critical: this is a Notice of Intent to Levy. Confirm the balance, contact the client immediately, and consider a CDP hearing request / installment agreement.";
  }
  if (c === "CP14" || c === "CP501" || c === "CP503") {
    return "Verify the assessed balance against the return; if correct, advise payment or an installment agreement before collection escalates.";
  }
  return "Review the notice against the filed return and advise the client.";
}

/** Exam / underreporter Transaction Codes. TC 420 (exam opened) + TC 424 (exam
 *  requested) are an actual examination → URGENT. TC 922 (review of potential
 *  unreported income — the AUR engine) precedes a CP2000 → ACTION. */
const EXAM_TC: Record<string, { severity: AlertSeverity; label: string }> = {
  "420": { severity: "urgent", label: "Examination of return opened" },
  "424": { severity: "urgent", label: "Examination requested" },
  "922": { severity: "action", label: "Review of unreported income (AUR)" },
};

const SEVERITY_RANK: Record<AlertSeverity, number> = {
  urgent: 0,
  action: 1,
  info: 2,
};

/** Balance-increase severity by size: a large new balance is urgent. */
function balanceIncreaseSeverity(delta: number): AlertSeverity {
  const d = Math.abs(delta);
  if (d >= 10_000) return "urgent";
  if (d >= 1_000) return "action";
  return "info";
}

/** A stable identity for a transcript line item, so re-posted-but-unchanged
 *  TCs don't re-alert. Code + date + rounded amount. */
function lineKey(li: TranscriptLineItem): string {
  return `${li.transactionCode}|${li.date}|${Math.round(toNum(li.amount))}`;
}

function money(n: number): string {
  const v = toNum(n);
  const sign = v < 0 ? "-" : "";
  return `${sign}$${Math.abs(v).toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

// ─── 5. detectTranscriptChanges ──────────────────────────────────────────────
/**
 * Diff a prior transcript snapshot against the current one and emit a sorted
 * (urgent → action → info) list of alerts:
 *   • balance_change — |Δ| > $1; an INCREASE is classified urgent/action/info
 *     by size; a DECREASE (payment posted / abatement) is info.
 *   • new_notice     — a CP code present now but not before; severity by code.
 *   • exam_flag      — a new exam/AUR Transaction Code (TC 420/424/922).
 *   • new_transaction— any other newly-posted TC → info.
 *
 * When `prior` is null this is the FIRST observation: we have no baseline, so
 * every existing notice + exam flag is surfaced as an INITIAL baseline alert
 * (so the firm reviews the starting state), but ordinary line items and the
 * opening balance are NOT alerted (they're the baseline, not a change). This
 * choice avoids a noisy first-run flood while still flagging anything the firm
 * must act on immediately.
 */
export function detectTranscriptChanges(args: {
  prior: TranscriptSnapshot | null;
  current: TranscriptSnapshot;
}): MonitorAlert[] {
  const { prior, current } = args;
  const alerts: MonitorAlert[] = [];

  // ── Notices ────────────────────────────────────────────────────────────
  const priorNoticeCodes = new Set(
    (prior?.notices ?? []).map((n) => `${n.code.toUpperCase()}|${n.date}`),
  );
  for (const n of current.notices ?? []) {
    const id = `${n.code.toUpperCase()}|${n.date}`;
    if (prior && priorNoticeCodes.has(id)) continue; // already seen
    const sev = noticeSeverity(n.code);
    const proposed = n.proposedAmount;
    const baselineNote = prior ? "" : " (initial baseline — first transcript pull)";
    alerts.push({
      kind: "new_notice",
      severity: sev,
      title: `IRS notice ${n.code.toUpperCase()} posted${baselineNote}`,
      detail:
        `${n.description}` +
        (proposed != null ? ` Proposed/assessed amount ${money(proposed)}.` : ""),
      amount: proposed != null ? toNum(proposed) : undefined,
      noticeCode: n.code.toUpperCase(),
      recommendedAction: noticeAction(n.code),
    });
  }

  // ── Line items: exam flags + other new TCs ───────────────────────────────
  const priorLineKeys = new Set((prior?.lineItems ?? []).map(lineKey));
  for (const li of current.lineItems ?? []) {
    if (prior && priorLineKeys.has(lineKey(li))) continue; // unchanged
    const exam = EXAM_TC[li.transactionCode];
    const baselineNote = prior ? "" : " (initial baseline — first transcript pull)";
    if (exam) {
      alerts.push({
        kind: "exam_flag",
        severity: exam.severity,
        title: `Exam/AUR flag — TC ${li.transactionCode}${baselineNote}`,
        detail: `${exam.label}: ${li.description} (posted ${li.date}${
          toNum(li.amount) !== 0 ? `, ${money(li.amount)}` : ""
        }).`,
        amount: toNum(li.amount) !== 0 ? toNum(li.amount) : undefined,
        recommendedAction:
          exam.severity === "urgent"
            ? "An examination has been opened. Contact the client, secure a Form 2848 if representation is needed, and assemble the supporting documentation for the return year."
            : "The IRS is reviewing potential unreported income (a CP2000 may follow). Pre-emptively reconcile reported income against third-party data.",
      });
      continue;
    }
    // On the first pull, ordinary line items are the baseline — not a change.
    if (!prior) continue;
    alerts.push({
      kind: "new_transaction",
      severity: "info",
      title: `New transcript transaction — TC ${li.transactionCode}`,
      detail: `${li.description} posted ${li.date}${
        toNum(li.amount) !== 0 ? ` (${money(li.amount)})` : ""
      }.`,
      amount: toNum(li.amount) !== 0 ? toNum(li.amount) : undefined,
      recommendedAction:
        "Informational — note the posting; no action unless it affects the balance or a notice references it.",
    });
  }

  // ── Balance change (only when we have a prior baseline) ───────────────────
  if (prior) {
    const delta = toNum(current.accountBalance) - toNum(prior.accountBalance);
    if (Math.abs(delta) > 1) {
      const increased = delta > 0;
      const sev = increased ? balanceIncreaseSeverity(delta) : "info";
      alerts.push({
        kind: "balance_change",
        severity: sev,
        title: increased
          ? `Account balance increased by ${money(delta)}`
          : `Account balance decreased by ${money(Math.abs(delta))}`,
        detail: `Balance moved from ${money(prior.accountBalance)} to ${money(
          current.accountBalance,
        )} (as of ${current.asOfDate}).`,
        amount: toNum(delta),
        recommendedAction: increased
          ? "Confirm what drove the increase (assessment / penalty / interest); reconcile against the filed return and any related notice."
          : "Likely a payment, refund offset, or abatement posted — confirm it matches the client's records.",
      });
    }
  }

  alerts.sort((a, b) => SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity]);
  return alerts;
}

// ─── 6. ResponseDraft ────────────────────────────────────────────────────────
export interface ResponseDraft {
  noticeCode: string;
  subject: string;
  bodyTemplate: string;
  groundingFacts: Array<{ label: string; ourValue: number; irsValue: number | null }>;
  disclaimers: string[];
}

const STANDARD_DISCLAIMERS = [
  "DRAFT — for CPA review. Do not send without a licensed preparer's review and sign-off.",
  "Figures are drawn from the firm's computed return for the year; verify against the source documents before relying on them.",
  "Prepared under a Form 8821 information authorization, which permits access to IRS account information but NOT representation. Filing a written response or appearing on the taxpayer's behalf requires a Form 2848 Power of Attorney.",
];

/** Map a notice code → the computed-return figures most relevant to grounding a
 *  response, plus a code-specific argument paragraph. */
function groundingForNotice(
  code: string,
  c: ComputedTaxReturn,
  notice: TranscriptSnapshot["notices"][number],
): { facts: ResponseDraft["groundingFacts"]; argument: string } {
  const upper = code.toUpperCase();
  const proposed = notice.proposedAmount != null ? toNum(notice.proposedAmount) : null;

  if (upper === "CP2000" || upper === "CP2501") {
    // AUR proposal: the IRS believes income was unreported. Ground the dispute
    // in the firm's computed totals so the CPA can confirm the item WAS on the
    // return (the common AUR false-positive — a 1099 the IRS double-counted or
    // matched to the wrong line).
    const facts: ResponseDraft["groundingFacts"] = [
      { label: "Total income reported (Form 1040 line 9)", ourValue: toNum(c.totalIncome), irsValue: null },
      { label: "Taxable interest reported (line 2b)", ourValue: toNum(c.form1099Summary?.interestIncome), irsValue: null },
      { label: "Ordinary dividends reported (line 3b)", ourValue: toNum(c.form1099Summary?.ordinaryDividends), irsValue: null },
      { label: "Total tax reported", ourValue: toNum(c.federalTaxLiability), irsValue: null },
      { label: "Additional tax the IRS proposes", ourValue: 0, irsValue: proposed },
    ];
    const argument =
      "The CP2000 is a proposal generated by the Automated Underreporter program from third-party information returns; it is not a final assessment (IRC §6213(b)). Our records show the income in question was included in the total income reported on the filed return. We therefore respectfully DISAGREE with the proposed change and ask that the proposal be withdrawn. The relevant amounts already reflected on the return are itemized below.";
    return { facts, argument };
  }

  if (upper === "CP14" || upper === "CP501" || upper === "CP503") {
    // Balance-due notice: ground in the computed balance owed so the CPA can
    // confirm whether the assessed balance matches the return.
    const facts: ResponseDraft["groundingFacts"] = [
      { label: "Total tax reported", ourValue: toNum(c.federalTaxLiability), irsValue: null },
      { label: "Federal tax withheld / paid", ourValue: toNum(c.federalTaxWithheld), irsValue: null },
      { label: "Balance owed per our computation", ourValue: Math.max(0, -toNum(c.federalRefundOrOwed)), irsValue: null },
      { label: "Balance the notice demands", ourValue: 0, irsValue: proposed },
    ];
    const argument =
      "This notice reflects a balance due on the account. We have reconciled it against the figures on the filed return (itemized below). If the firm's computed balance matches the notice, we will advise the client on payment or an installment agreement; if it does not, we will dispute the difference with the supporting detail.";
    return { facts, argument };
  }

  if (upper === "CP504" || upper === "CP504B" || upper === "LT11") {
    const facts: ResponseDraft["groundingFacts"] = [
      { label: "Total tax reported", ourValue: toNum(c.federalTaxLiability), irsValue: null },
      { label: "Federal tax withheld / paid", ourValue: toNum(c.federalTaxWithheld), irsValue: null },
      { label: "Balance the levy notice demands", ourValue: 0, irsValue: proposed },
    ];
    const argument =
      "This is a Notice of Intent to Levy — a collection-enforcement escalation. This requires immediate attention. We are reconciling the demanded balance against the filed return and will advise the client on resolving the balance and, if appropriate, requesting a Collection Due Process hearing.";
    return { facts, argument };
  }

  // Generic posted notice.
  const facts: ResponseDraft["groundingFacts"] = [
    { label: "Total income reported (line 9)", ourValue: toNum(c.totalIncome), irsValue: null },
    { label: "Total tax reported", ourValue: toNum(c.federalTaxLiability), irsValue: null },
    { label: "Amount referenced by the notice", ourValue: 0, irsValue: proposed },
  ];
  const argument =
    "We have reviewed this notice against the figures on the filed return (itemized below) and will advise the client accordingly.";
  return { facts, argument };
}

// ─── 7. draftNoticeResponse ──────────────────────────────────────────────────
/**
 * Produce a DETERMINISTIC, professional response-letter template that grounds
 * its argument in the firm's `computed` return figures. No LLM call — every
 * figure is computed here; a downstream route may polish the prose under a
 * §7216 consent, but it may not alter the numbers.
 *
 * `groundingFacts` pairs each of our computed values (`ourValue`) against the
 * IRS's proposed/assessed figure (`irsValue`, null when the IRS gives no number
 * for that line). `disclaimers` always include the CPA-review + draft + 8821
 * scope notes.
 */
export function draftNoticeResponse(args: {
  notice: TranscriptSnapshot["notices"][number];
  computed: ComputedTaxReturn;
  clientFirstName: string;
  clientLastName: string;
  preparerName?: string;
  asOfDate: string;
}): ResponseDraft {
  const { notice, computed, clientFirstName, clientLastName, preparerName, asOfDate } = args;
  const code = notice.code.toUpperCase();
  const fullName = `${clientFirstName} ${clientLastName}`.trim();
  const taxYear = toNum(computed.taxYear);
  const { facts, argument } = groundingForNotice(code, computed, notice);

  const subject = `Response to IRS Notice ${code} — ${fullName}, Tax Year ${taxYear}`;

  // Render the grounding facts as a plain-text table the CPA can verify.
  const factLines = facts
    .map((f) => {
      const ours = money(f.ourValue);
      const irs = f.irsValue == null ? "—" : money(f.irsValue);
      return `    • ${f.label}: our return ${ours} | IRS ${irs}`;
    })
    .join("\n");

  const signoff = preparerName ? preparerName : "[Preparer name — CPA review required]";

  const bodyTemplate = [
    `[DRAFT — CPA REVIEW REQUIRED BEFORE SENDING]`,
    ``,
    `Date: ${asOfDate}`,
    ``,
    `Internal Revenue Service`,
    `Re: Notice ${code}`,
    `Taxpayer: ${fullName}`,
    `Tax Year: ${taxYear}`,
    ``,
    `To Whom It May Concern:`,
    ``,
    `We are writing on behalf of ${fullName} regarding IRS Notice ${code} for tax year ${taxYear}.`,
    ``,
    argument,
    ``,
    `Relevant figures from the filed return:`,
    factLines,
    ``,
    `We respectfully request that the IRS review the enclosed information. Please contact our office with any questions.`,
    ``,
    `Sincerely,`,
    signoff,
    ``,
    `Authorization: Form 8821 (Tax Information Authorization) on file. This letter is a draft prepared for the taxpayer's records and the preparer's review; it does not constitute representation before the IRS (which would require a Form 2848 Power of Attorney).`,
  ].join("\n");

  return {
    noticeCode: code,
    subject,
    bodyTemplate,
    groundingFacts: facts,
    disclaimers: [...STANDARD_DISCLAIMERS],
  };
}
